/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.ButtonModel;
import libClases.Algoritmo;
import libClases.Fichero;
import libClases.Grafica;
import libClases.Punto;


/**
 * @version 09/11/24
 * @author Antonio Abad HErnández Gálvez
 * Frame del case 5 del Menu
 */
public class CompararDosAlgoritmos extends javax.swing.JFrame {
      
    private boolean caso_peor;
    
    public CompararDosAlgoritmos(boolean peor_caso)
    {
        this.caso_peor=peor_caso;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioEstrategiaA = new javax.swing.ButtonGroup();
        radioEstrategiaB = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbExhaustivoA = new javax.swing.JRadioButton();
        rbExhaustivoPodaA = new javax.swing.JRadioButton();
        rbDV_A = new javax.swing.JRadioButton();
        rbDVM_A = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rbExhaustivoB = new javax.swing.JRadioButton();
        rbExhaustivoPodaB = new javax.swing.JRadioButton();
        rbDV_B = new javax.swing.JRadioButton();
        rbDVM_B = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCompararEstrategias = new javax.swing.JButton();
        lError = new javax.swing.JLabel();

        radioEstrategiaA.add(rbExhaustivoA);
        radioEstrategiaA.add(rbExhaustivoPodaA);
        radioEstrategiaA.add(rbDV_A);
        radioEstrategiaA.add(rbDVM_A);

        radioEstrategiaB.add(rbExhaustivoB);
        radioEstrategiaB.add(rbExhaustivoPodaB);
        radioEstrategiaB.add(rbDV_B);
        radioEstrategiaB.add(rbDVM_B);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Comparar dos Estrategias");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(200, 200));
        setLocationByPlatform(true);
        setName("fComparaDosEstrategias"); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecciona Dos Estrategias para comparar");
        jLabel1.setName(""); // NOI18N

        rbExhaustivoA.setMnemonic('0');
        rbExhaustivoA.setText("Exhaustivo");
        rbExhaustivoA.setActionCommand("0");
        rbExhaustivoA.setName("rbExhaustivoA"); // NOI18N
        rbExhaustivoA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbExhaustivoAMouseClicked(evt);
            }
        });
        rbExhaustivoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbExhaustivoAActionPerformed(evt);
            }
        });

        rbExhaustivoPodaA.setMnemonic('1');
        rbExhaustivoPodaA.setText("Exhaustivo Poda");
        rbExhaustivoPodaA.setToolTipText("");
        rbExhaustivoPodaA.setActionCommand("1");
        rbExhaustivoPodaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbExhaustivoPodaAActionPerformed(evt);
            }
        });

        rbDV_A.setMnemonic('2');
        rbDV_A.setText("Divide y Vencerás");
        rbDV_A.setToolTipText("");
        rbDV_A.setActionCommand("2");
        rbDV_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDV_AActionPerformed(evt);
            }
        });

        rbDVM_A.setMnemonic('3');
        rbDVM_A.setText("Divide y Vencerás Mejorado");
        rbDVM_A.setToolTipText("");
        rbDVM_A.setActionCommand("3");
        rbDVM_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDVM_AActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setText("VS");

        rbExhaustivoB.setMnemonic('0');
        rbExhaustivoB.setText("Exhaustivo");
        rbExhaustivoB.setActionCommand("0");
        rbExhaustivoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbExhaustivoBActionPerformed(evt);
            }
        });

        rbExhaustivoPodaB.setMnemonic('1');
        rbExhaustivoPodaB.setText("Exhaustivo Poda");
        rbExhaustivoPodaB.setToolTipText("");
        rbExhaustivoPodaB.setActionCommand("1");
        rbExhaustivoPodaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbExhaustivoPodaBActionPerformed(evt);
            }
        });

        rbDV_B.setMnemonic('2');
        rbDV_B.setText("Divide y Vencerás");
        rbDV_B.setToolTipText("");
        rbDV_B.setActionCommand("2");
        rbDV_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDV_BActionPerformed(evt);
            }
        });

        rbDVM_B.setMnemonic('3');
        rbDVM_B.setText("Divide y Vencerás Mejorado");
        rbDVM_B.setToolTipText("");
        rbDVM_B.setActionCommand("3");
        rbDVM_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDVM_BActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Estrategia A");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Estrategia B");

        btnCompararEstrategias.setText("Comparar");
        btnCompararEstrategias.setActionCommand("bCompararDosEstrategias");
        btnCompararEstrategias.setName("bCompararDos"); // NOI18N
        btnCompararEstrategias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompararEstrategiasActionPerformed(evt);
            }
        });

        lError.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lError.setForeground(new java.awt.Color(153, 0, 0));
        lError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lError.setToolTipText("");
        lError.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lError.setRequestFocusEnabled(false);
        lError.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(btnCompararEstrategias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(353, 353, 353)
                                        .addComponent(jLabel4)))
                                .addGap(89, 89, 89))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbExhaustivoA)
                                    .addComponent(rbDVM_A)
                                    .addComponent(rbDV_A)
                                    .addComponent(rbExhaustivoPodaA))
                                .addGap(54, 54, 54)
                                .addComponent(jLabel2)
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbExhaustivoB)
                                    .addComponent(rbExhaustivoPodaB)
                                    .addComponent(rbDV_B)
                                    .addComponent(rbDVM_B))))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addComponent(lError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbExhaustivoA)
                            .addComponent(rbExhaustivoB))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbExhaustivoPodaA)
                            .addComponent(rbExhaustivoPodaB))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(rbDV_A))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(rbDV_B)))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbDVM_A)
                            .addComponent(rbDVM_B))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(71, 71, 71)
                        .addComponent(btnCompararEstrategias)
                        .addGap(29, 29, 29)))
                .addComponent(lError, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jLabel1.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompararEstrategiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompararEstrategiasActionPerformed
        
        // Creamos las dos variables que contienen las estrategias seleccionadas
        ButtonModel opcionA = radioEstrategiaA.getSelection();
        ButtonModel opcionB = radioEstrategiaB.getSelection();
        
        String estrategia_A="";
        String estrategia_B="";
        
        // Limpiamos el mensaje de error de la pantalla cuando ya NO seleccionamos el mismo algoritmo
        lError.setText(""); 
        
        // Comprobamos que no podamos seleeccionar una Comparativa para el mismo algoritmo, es decir, nomAlgoritmo1 != nomAlgoritmo2
        if ((rbExhaustivoA.isSelected() && rbExhaustivoB.isSelected()) ||
            (rbExhaustivoPodaA.isSelected() && rbExhaustivoPodaB.isSelected()) ||
            (rbDV_A.isSelected() && rbDV_B.isSelected()) ||
            (rbDVM_A.isSelected() && rbDVM_B.isSelected()))
        {
            lError.setText("No es posible comparar la Misma Estrategia");
        }
        else
        {
            //ejecuta la comparativa
            estrategia_A=opcionA.getActionCommand();
            estrategia_B=opcionB.getActionCommand();
    
            // Codigo del Case 5
            Punto[] v_puntos; // Vector de puntos generado aleatoriamente
            Punto[] v_algoritmo=null; // Vector de Puntos que devuelve el Algortimo 'i'
            Punto[] v_copia = null; // Vector de Puntos que es una copia del Vector Original cargado en Memoria para que cada Algoritmo trabaje con el Vector Original
            double tInicio = 0; // Tiempo Inicial de la ejecucion del Algoritmo
            double tFin = 0; // Tiempo Final de la ejecucion del Algoritmo
            double duracion = 0; // Tiempo total de duracion de la ejecucion del Algoritmo (tFin - tInicio)
            double dis_min = 0; // Distancia minima entre los 2 Puntos mas cercanos del Fichero
                    
            String v_nomAlgoritmo[]=new String[4]; // Vector que contiene el Nombre de los 4 Algoritmos posibles que hay en el Programa
            String v_nomAlgoritmoSeleccionado[]=new String[2]; // Vector que contiene el Nombre de los 2 Algoritmos seleccionados para compararlos
            String nomAlgoritmo; // Contiene el Nombre de los 2 Algoritmos Concatenados
            StringBuilder salida=new StringBuilder(); // Salida de la Consola que ahora mostramos en el Frame
            String tituloVentana; // Titulo de la ventana de la compartiva de los 2 algoritmos
            
            // Variables para realizar el Caso Medio
            int numCasoMedio = 100; // Numero de Vectores de Puntos que queremos generar aleatoriamente para realizar el Caso Medio
            int talla_inicial = 1000;
            int talla_final = 5000;
            int incremento = 1000;
            int num_tallas = talla_final / incremento; // Determina la longitud del Vector de tiempos que vamos a crear
            int talla=talla_inicial; // Talla para mostrarla por Consola
                    
            // Variables para almacenar los tiempos de cada Algoritmo
            double v_tiempo_acumulado[] = new double[4]; // Vector de tiempos para almacenar el tiempo de cada Algoritmo despues de hacer el Caso Medio
            double v_tiempos_A1[]=new double[num_tallas]; // Vector de tiempos del Algoritmo 1
            double v_tiempos_A2[]=new double[num_tallas]; // Vector de tiempos del Algoritmo 2
            int pos_tiempo=0;
                    
            // Variables para almacenar las distancias calculadas de cada Algoritmo
            long v_calculadas[]=new long[2]; // Vector que contiene el nº de llamadas al metodo 'distancia()' resultante de cada Algoritmo despues de hacer el Caso Medio
            long v_calculadas_A1[]=new long[num_tallas]; // Vector de distancias calculadas del Algoritmo 1
            long v_calculadas_A2[]=new long[num_tallas]; // Vector de distancias calculadas del Algoritmo 2
            int pos_calculadas=0;
            int opc_1; // Contiene la posicion del radio button del primer Algoritmo (columna izquierda)
            int opc_2; // Contiene la posicion del radio button del segundo Algoritmo (columna derecha)
            
            v_nomAlgoritmo[0] = "Exhaustivo";
            v_nomAlgoritmo[1] = "ExhaustivoPoda";
            v_nomAlgoritmo[2] = "DivideVenceras";
            v_nomAlgoritmo[3] = "DyVMejorado";
                    
            // Escribimos el Nombre de los 2 Algorimos que queremos comparar en el Vector 'v_nomAlgoritmo'
            opc_1=Integer.parseInt(estrategia_A);
            opc_2=Integer.parseInt(estrategia_B);
            
            v_nomAlgoritmoSeleccionado[0]=v_nomAlgoritmo[opc_1]; 
            v_nomAlgoritmoSeleccionado[1]=v_nomAlgoritmo[opc_2];
                    
            nomAlgoritmo=v_nomAlgoritmoSeleccionado[0]+v_nomAlgoritmoSeleccionado[1];
                    
            // Realizamos el Caso Medio para cada Algoritmo (generamos 100 vectores de Puntos aleatorios) para que no se produzcan resultados inconsistentes
            for (int i=talla_inicial; i<=talla_final; i=i+incremento)
            {
                for (int j=0; j<numCasoMedio; j++) // Generamos 'numCasoMedio=10' vectores de Puntos para realizar el Caso Medio y NO generar 1 unico Vector de Puntos que pueda provocar resultados incoherentes
                {
                    v_puntos=MenuGrafico.generarVector(i); // Generamos un vector de Puntos aleatorios de talla 'i'  

                    // Comparamos cada algoritmo para cada vector de puntos generados y vamos sumando los tiempos de cada Algoritmos (Igual que en el case 3)
                    for(int k=0; k<2; k++)
                    {
                        v_copia=MenuGrafico.copiarVector(v_puntos); // Copiamos los Datos del Vector para trabajar con el y NO modificar los valores del Vector Original

                        Algoritmo.setContador(0); // Reseteamos el Contador del numero de llamadas al metodo 'distancia()' para el Algoritmo 'k'
                        Algoritmo.resetDistanciaMinima(); // Resetamos el valor de la Distancia Minima para el Algoritmo 'k'
                        tInicio = System.nanoTime(); // Iniciamos el tiempo del Algoritmo 'i'
                        switch (v_nomAlgoritmoSeleccionado[k])
                        {
                            case "Exhaustivo":
                            {
                                v_algoritmo = Algoritmo.busquedaExhaustiva(v_copia, 0, v_copia.length - 1);
                            };break;

                            case "ExhaustivoPoda":
                            {
                                Algoritmo.QuickSort(v_copia, 0, v_copia.length - 1, 'x'); // Ordenamos el Vector de Puntos antes de llamar al Algoritmo
                                v_algoritmo = Algoritmo.busquedaExhaustivaPoda(v_copia, 0, v_copia.length - 1);
                            };break;

                            case "DivideVenceras":
                            {
                                Algoritmo.QuickSort(v_copia, 0, v_copia.length - 1, 'x'); // Ordenamos el Vector de Puntos antes de llamar al Algoritmo
                                v_algoritmo = Algoritmo.busquedaDyV(v_copia, 0, v_copia.length - 1);
                            };break;

                            case "DyVMejorado":
                            {
                                Algoritmo.QuickSort(v_copia, 0, v_copia.length-1, 'x'); // Ordenamos el Vector de Puntos antes de llamar al Algoritmo
                                v_algoritmo=Algoritmo.busquedaDyV_mejorada(v_copia, 0, v_copia.length-1);
                            };break;
                        }
                                
                        // Calculamos la distancia minima entre los 2 Puntos mas cercanos del Ficheros calculados por el Algoritmo 'i'
                        dis_min = Algoritmo.getDistanciaMinima();
                        // Calculamos la duracion del Algoritmo 'i'
                        tFin = System.nanoTime();
                        duracion = (tFin - tInicio) / 1e6; // Convertimos la duracion en 'ns' a 'ms'
                        v_tiempo_acumulado[k] = v_tiempo_acumulado[k] + duracion; // Acumulamos la duracion de cada Algoritmo en el Vector de tiempos 'v_tiempos' para ver el tiempo total que ha tardado cada Algoritmo y despues hacer el Caso Medio
                        v_calculadas[k] = v_calculadas[k] + Algoritmo.getContador(); // Acumulamos las calculadas de cada Algoritmo en el Vector de calculadas 'v_calculadas' para ver el nº de distancias calculadas en total que ha realizado cada Algoritmo
                    }
                }
                        
                // Almacenamos los tiempos y las distancias calculadas de cada Algoritmo
                v_tiempos_A1[pos_tiempo]=v_tiempo_acumulado[0]/num_tallas;
                v_tiempos_A2[pos_tiempo]=v_tiempo_acumulado[1]/num_tallas;
                pos_tiempo++;
                        
                v_calculadas_A1[pos_calculadas]=v_calculadas[0];
                v_calculadas_A2[pos_calculadas]=v_calculadas[1];
                pos_calculadas++;
            }
                    
            // Mostramos los Resultados de los Algoritmos para cada talla
            // Escribimos las Cabeceras de la Salida por Pantalla
            salida.append(String.format("%-10s %-16s %-16s %-16s %-16s%n", "", v_nomAlgoritmoSeleccionado[0], v_nomAlgoritmoSeleccionado[1], v_nomAlgoritmoSeleccionado[0], v_nomAlgoritmoSeleccionado[1]));
            salida.append(String.format("%-10s %-16s %-16s %-16s %-16s%n", "Talla", "Tiempo (ms)", "Tiempo (ms)", "Calculadas", "Calculadas"));
            for(int i=0;i<num_tallas; i++)
            {
                salida.append(String.format("%-10s ", talla));
                salida.append(String.format("%-16.6f ", v_tiempos_A1[i]));
                salida.append(String.format("%-16.6f ", v_tiempos_A2[i]));
                salida.append(String.format("%-16d ", v_calculadas_A1[i]));
                salida.append(String.format("%-16d ", v_calculadas_A2[i]) + "\n");

                talla=talla+incremento;
            }

            // Generamos el Fichero .DAT con el resultado de los Algoritmos
            Fichero.escribirFicheroDAT_comparativa(v_nomAlgoritmoSeleccionado, v_tiempos_A1, v_tiempos_A2, v_calculadas_A1, v_calculadas_A2, talla_inicial, incremento);
            salida.append("Fichero '" + nomAlgoritmo + ".dat' generado");
            
            // Comprobamos si el Caso Peor esta activado para mostrarlo en el Nombre de la Grafica
            if(this.caso_peor==true)
            {
                nomAlgoritmo=nomAlgoritmo + " (Peor Caso)";
            }
            
            // Mostramos por Pantalla el resultado
            VentanaResultado v = new VentanaResultado();
            tituloVentana="Resultado de COMPARAR 2 ESTRATEGIAS";
            v.setLocation(0, 33);
            v.setSize(700, 300);
            v.setTitle(tituloVentana);
            if(this.caso_peor==true) // Si el Caso Peor esta activado, cambiamos el titulo de la Ventana del muestreo de tiempos
            {
                tituloVentana=tituloVentana+ " (Peor Caso)";
                v.setTitle(tituloVentana);
            }
            v.mostrarVentana(salida.toString());
            v.setVisible(true);
            
            // Generamos la grafica comparativa de los 2 Algoritmos
            Grafica g=new Grafica(nomAlgoritmo, "Talla", "Tiempo (ms)", 2); // Grafica de tipo 2 (Comparativa de 2 Algoritmos)
            g.setLocation(705, 33);
            g.agregarGraficaComparativa(v_nomAlgoritmoSeleccionado, v_tiempos_A1, v_tiempos_A2, talla_inicial, incremento);
            g.setVisible(true);
        }
    }//GEN-LAST:event_btnCompararEstrategiasActionPerformed

    private void rbExhaustivoAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbExhaustivoAMouseClicked
        
    }//GEN-LAST:event_rbExhaustivoAMouseClicked

    private void rbExhaustivoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbExhaustivoAActionPerformed
        
        rbExhaustivoA.setActionCommand("0");
    }//GEN-LAST:event_rbExhaustivoAActionPerformed

    private void rbExhaustivoPodaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbExhaustivoPodaAActionPerformed
        
        rbExhaustivoPodaA.setActionCommand("1");
    }//GEN-LAST:event_rbExhaustivoPodaAActionPerformed

    private void rbDV_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDV_AActionPerformed
        
        rbDV_A.setActionCommand("2");
    }//GEN-LAST:event_rbDV_AActionPerformed

    private void rbDVM_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDVM_AActionPerformed
        
        rbDVM_A.setActionCommand("3");
    }//GEN-LAST:event_rbDVM_AActionPerformed

    private void rbExhaustivoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbExhaustivoBActionPerformed
        
        rbExhaustivoB.setActionCommand("0");
    }//GEN-LAST:event_rbExhaustivoBActionPerformed

    private void rbExhaustivoPodaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbExhaustivoPodaBActionPerformed
       
        rbExhaustivoPodaB.setActionCommand("1");
    }//GEN-LAST:event_rbExhaustivoPodaBActionPerformed

    private void rbDV_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDV_BActionPerformed
       
        rbDV_B.setActionCommand("2");
    }//GEN-LAST:event_rbDV_BActionPerformed

    private void rbDVM_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDVM_BActionPerformed
       
        rbDVM_B.setActionCommand("3");
    }//GEN-LAST:event_rbDVM_BActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompararEstrategias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lError;
    private javax.swing.ButtonGroup radioEstrategiaA;
    private javax.swing.ButtonGroup radioEstrategiaB;
    private javax.swing.JRadioButton rbDVM_A;
    private javax.swing.JRadioButton rbDVM_B;
    private javax.swing.JRadioButton rbDV_A;
    private javax.swing.JRadioButton rbDV_B;
    private javax.swing.JRadioButton rbExhaustivoA;
    private javax.swing.JRadioButton rbExhaustivoB;
    private javax.swing.JRadioButton rbExhaustivoPodaA;
    private javax.swing.JRadioButton rbExhaustivoPodaB;
    // End of variables declaration//GEN-END:variables
}
