/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;
import libClases.Fichero;

/**
 * @version 09/11/24
 * @author Antonio Abad Hernandez Galvez
 * Frame para el case 1 del Menu
 */
public class CrearFicheroAleatorio extends javax.swing.JFrame {
    
    public CrearFicheroAleatorio()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ltamano = new javax.swing.JLabel();
        campo_tamano_fichero = new javax.swing.JSpinner();
        crear_fichero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CREAR UN FICHERO TSP ALEATORIO");
        setLocation(new java.awt.Point(600, 150));
        setName("fCrearFicheroAleatorio"); // NOI18N
        setResizable(false);

        ltamano.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ltamano.setText("Número de Puntos a Generar :");
        ltamano.setToolTipText("Indica cuantos puntos se van a generar aleatoriamente para almacenar en el Fichero ");

        campo_tamano_fichero.setModel(new javax.swing.SpinnerNumberModel(2, 2, Integer.MAX_VALUE, 1));
        campo_tamano_fichero.setToolTipText("Selecciona número de puntos");
        campo_tamano_fichero.setName("campo_tamano_fichero"); // NOI18N
        campo_tamano_fichero.setValue(2);

        crear_fichero.setText("Crear Fichero");
        crear_fichero.setToolTipText("Pulsa para generar el Fichero");
        crear_fichero.setActionCommand("crear_fichero");
        crear_fichero.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                crear_ficheroAncestorRemoved(evt);
            }
        });
        crear_fichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_ficheroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(ltamano)
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(campo_tamano_fichero)
                    .addComponent(crear_fichero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(ltamano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_tamano_fichero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crear_fichero)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        campo_tamano_fichero.getAccessibleContext().setAccessibleName("");
        crear_fichero.getAccessibleContext().setAccessibleName("crear_fichero");

        getAccessibleContext().setAccessibleName("fCrearAleatorio");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crear_ficheroAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_crear_ficheroAncestorRemoved
        
    }//GEN-LAST:event_crear_ficheroAncestorRemoved

    private void crear_ficheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_ficheroActionPerformed
        
        Integer tamano=(Integer) campo_tamano_fichero.getValue(); // Obtenemos el valor del tamaño del fichero que queremos crear
        String a;
        
        a=Fichero.escribirFichero(tamano);
        
        JOptionPane.showMessageDialog(null,"Fichero 'dataset " + tamano + ".tsp' generado con éxito.", "Crear TSP Aleatorio", JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
    }//GEN-LAST:event_crear_ficheroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JSpinner campo_tamano_fichero;
    private javax.swing.JButton crear_fichero;
    private javax.swing.JLabel ltamano;
    // End of variables declaration//GEN-END:variables
}
