/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Font;
import javax.swing.JFrame;

/**
 *
 * @author Antonio Abad
 */
public class VentanaResultado extends javax.swing.JFrame {

    public VentanaResultado() {
        // El titulo lo escribimos desde el Boton del case en el Menu Principal
        // El tamaño lo redimensionamos desde el 'Design' del Frame
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        initComponents();
    }
    
    public void mostrarVentana(String resultado)
    {
        this.areaTexto.setFont(new Font("Monospaced", Font.PLAIN, 15)); // Cambiamos la fuente para poder formatearla con 'String.format()'
        this.areaTexto.setText(resultado);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_case3 = new javax.swing.JPanel();
        img_case3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1536, 300));
        setPreferredSize(new java.awt.Dimension(1536, 300));

        img_case3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_case3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/img_info.jpg"))); // NOI18N

        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane1.setViewportView(areaTexto);

        javax.swing.GroupLayout panel_case3Layout = new javax.swing.GroupLayout(panel_case3);
        panel_case3.setLayout(panel_case3Layout);
        panel_case3Layout.setHorizontalGroup(
            panel_case3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1536, Short.MAX_VALUE)
            .addComponent(img_case3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_case3Layout.setVerticalGroup(
            panel_case3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_case3Layout.createSequentialGroup()
                .addComponent(img_case3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_case3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_case3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JLabel img_case3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_case3;
    // End of variables declaration//GEN-END:variables
}
